import '@radix-ui/themes/styles.css';
import { Metadata  } from 'next'
import { Inter } from 'next/font/google'
import './theme-config.css';
import './admin.css';
import ProgressProvider from './components/progressbar/ProgressProvider';
import { Box, Grid, Theme  } from '@radix-ui/themes';
import SideBar from './components/SideBar';
import Header from './components/Header';
import AuthProvider from '../auth/AuthProvider';


// Initializing Inter font with Latin subset
const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
 })

// Metadata for the root layout
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ProgressProvider>
            <Theme appearance='light' accentColor='violet'>
              <Grid align="start" columns="auto 1fr">
                <Grid align="start" className='h-[100vh] content-start w-80 bg-slate-800'>
                  <figure className='w-full py-1 h-20'>
                    <img className='w-full h-full object-contain' src="/images/Untitled.png" alt="" />
                  </figure>
                  <SideBar/>
                </Grid>
                <Grid align="start" className='grid grid-cols-1 content-start items-start'>
                  <Header/>
                  <Box className='p-6'>
                    {children}
                  </Box>
                </Grid>
              </Grid>
            </Theme>
          </ProgressProvider>
        </AuthProvider>
    </body>
    </html>
  )
}
